### PR TITLE
Initial contribution of dash-licenses-wrapper

### PR DESCRIPTION
**Pull request by marcdumais-work**
# Description

This contribution provides a wrapper, to make it easier to integrate and run dash-licenses, in Eclipse Foundation projects repositories. It's mainly aiming to cover JavaScript and TypeScript projects, but might be usable in others too.

Once published to `npm`, the wrapper can be installed as a devDependency and used to run license checks locally on a developer's laptop and also as part of GitHub CI, using a provided example `workflow` file.

See README.md for more details

## Testing

This contribution includes some minimal tests, run from a `CI Tests` GitHub workflow. There is a second `3PP License Check` workflow that uses a trick to install the wrapper as a pseudo npm package and then run a license check, which gives a preview of what it will look-like when integrated to other projects/repos. Until this is published to `npm`, a similar trick could be used to install it temporarily, for a quick check.

I created a test PR on my fork so they would run. See the result of the workflow runs below: 
[CI Tests workflow](https://github.com/marcdumais-work/nodejs-wrapper/actions/runs/6851310564/job/18627305100?pr=1)
[3PP License check workflow](https://github.com/marcdumais-work/nodejs-wrapper/actions/runs/6851310560/job/18627305137?pr=1)

Note: An earlier version of this contribution was first proposed as an addition to the [dash-licenses repository](https://github.com/eclipse/dash-licenses/pull/278) but since there are no direct dependencies to that repo's content, it was deemed better to have it in on its own.

### CODE REVIEW

**Comment by waynebeaton** [comment]
IP Review initiated: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11530

**Comment by marcdumais-work** [comment]
Oops - there was a left-over mention of the secondary license, left from the original Theia sources - corrected now. Can you re-run Scancode?

**Comment by marcdumais-work** [comment]
@waynebeaton friendly ping :)

**Comment by marcdumais-work** [comment]
@waynebeaton Any thoughts about how to proceed to publish this to `npm`? Does the project perhaps already have a npm organization or account?

If not, I could go ahead and create a free organization with an appropriate name (`eclipse-dash`?), temporarily add myself as a member and manually publish a first version of the package. Then, time permitting, I would try to figure-out automated publishing from CI if possible (from my fork first, where I can set GitHub secrets). In that scenario, I would plan to transfer ownership of the org to Webmaster, and let them manage it with the project's input.  I have similarly transferred the Theia npm org a while ago. This approach would permit having this out ASAP and give me latitude to experiment with the automated publish setup, before handing-over the keys to the npm account.

However I am open to doing this however you think is best. WDYT?

**Comment by waynebeaton** [comment]
I have no relevant experience in this matter.

It seems to me that the path that you've charted is our best bet.

**Pull request merged**
